### PR TITLE
initial commit of game highlights detection

### PR DESCRIPTION
**Pull request by efinery**
Hi Seb,

I've quickly sketched out a base to work from for the highlights detection. It's much easier for me to explain in code than email. It's all decoupled and very testable. I usually never checkin without tests, but I'm trying to get as many hours in with ZBrush as I can today ;)

Cheers,
Hugh

### CODE REVIEW

**Comment by sebastientromp** [comment]
Had a quick look, that's pretty clear now :) I'm leaving soon, and will look more deeply into it either tonight or tomorrow at the latest.

I'll also try to build the glue in ReplayFileReader to be able to test with a real game and see how it goes, Looks promising!

As for tests, for now I'm more interested in having something that works to show what can be done, even if there are bugs and regressions now and then (I think it shows in my own commits :p), so don't worry too much for now

Thanks!

Seb

**Comment by efinery** [comment]
Great, looking forward to seeing what you can do with it.


Regards,

Hugh

*Hugh O'Donnell*
E-Finery Ltd.
| m: +44 777 9341283, +39 392 311 5811 | e: efinery@gmail.com
<efinery@gmail.com>
<http://uk.linkedin.com/pub/hugh-o-donnell/4/609/690/>

**Comment by sebastientromp** [comment]
I've done a quick glue to detect turns with more than a given threshold to a given target. Should I just push to update your pull request branch, or should I create another branch and push it there?

**Comment by efinery** [comment]
Hi Seb,

You can just push it to your master branch and I can then sync with it. I
had to fork and create a pull request since I didn't have any permissions
to push to your master. If there were a lot of people working on it you may
consider branches, but I really don't see the need. Even if 10 people were
working on the codebase they wouldn't be stepping on each other's toes as
they'd be working on separate rules, and the only conflicts would be on the
Factory which would still merge without issue.


Regards,

Hugh

*Hugh O'Donnell*
E-Finery Ltd.
| m: +44 777 9341283, +39 392 311 5811 | e: efinery@gmail.com
<efinery@gmail.com>
<http://uk.linkedin.com/pub/hugh-o-donnell/4/609/690/>

**Comment by sebastientromp** [comment]
Agree we don't need branches here. 

I had checked out your PR and put my code directly on it, and thought I could just merge the code locally and push it back, but didn't realize it would keep the link with the original PR.

**Comment by sebastientromp** [comment]
Quick summary of the changes:

* I moved all your code to a dedicated package
* Moved the hard-coded test data to a unit test
* Changed a bit the signature of the damageTaken method to accept also the entity that took damage
* Added the glue between the game object and the events

**Comment by efinery** [comment]
Hi Seb,

I'm not so used to forking as I tend to work in a team where we all work on
the same codebase in difference branches. If you accept my pull request, it
will pull my changes to your main repo. You are the original owner, so you
should always be checking in to your repo and I can then pickup your
changes.

I'll have a look when I have time ;)


Regards,

Hugh

*Hugh O'Donnell*
E-Finery Ltd.
| m: +44 777 9341283, +39 392 311 5811 | e: efinery@gmail.com
<efinery@gmail.com>
<http://uk.linkedin.com/pub/hugh-o-donnell/4/609/690/>

**Comment by sebastientromp** [comment]
Understood :)

So the code is in master now, feel free to check it out anytime :)

**Comment by efinery** [comment]
Hi Seb,

Alternatively you could simply give me access permission to your repo. I'll
check it out when I have time, I'm traveling for the next 2 weekends.


Regards,

Hugh

*Hugh O'Donnell*
E-Finery Ltd.
| m: +44 777 9341283, +39 392 311 5811 | e: efinery@gmail.com
<efinery@gmail.com>
<http://uk.linkedin.com/pub/hugh-o-donnell/4/609/690/>

**Comment by sebastientromp** [comment]
Will be the easiest, yes. Just granted you write rights on the repo

**Pull request merged**
